### ISSUE TITLE
Unknown dependency: simulation/smurf_parser

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-cpp/package_set#1]
Error message:

manifest file:

```
package_sets:
    - github: rock-core/package_set
    - github: rock-core/rock-package_set
    - github: rock-cpp/package_set

layout:
    - tools/pocolog
    - tools/pocolog_cpp
    - tools/orocos_cpp
```

```
$ aup
tools/orocos_cpp is selected in the manifest or on the command line, but
it is excluded from the build: it depends on simulation/smurf_parser, which
is neither the name of a source package, nor an osdep that is available on
this operating system (dependency chain: tools/orocos_cpp>tools/smurf)
```

Possible fix: import the package set `github: rock-simulation/simulation-package_set`.
